### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pavankum**

### CODE REVIEW

**Review by jchodera — APPROVED** [review]
This is great! Thanks!

**Comment by jchodera** [comment]
@peastman : What do you think of integrating the nice table @pavankum created here into the `README.md`?

**Comment by peastman** [comment]
A table sounds good.  What information do we want to include in it?  Links to PRs in `qca-dataset-submission` repo probably aren't relevant to most users.  Perhaps something similar to Table 1 in the paper draft?

**Comment by jchodera** [comment]
>  A table sounds good. What information do we want to include in it? Links to PRs in qca-dataset-submission repo probably aren't relevant to most users. Perhaps something similar to Table 1 in the paper draft?

The information from Table 1 (including the number of molecules and snapshots) would be useful! The links to the original PRs would be useful to retain because they contain important provenance information for the QCFractal calculation.

**Comment by jchodera** [comment]
Closing this, since @peastman has updated the README in #20.

**Pull request closed without merging**
