### PR TITLE
Added instructions on citing the dataset

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by jchodera** [comment]
This is good!

What about adding the Zenodo badge to the README or the release?
```
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7084690.svg)](https://doi.org/10.5281/zenodo.7084690)
```
And potentially also adding the bibtex citation block to the README to make it easy to copy-and-paste in the correct format? This is from the arXiv page:
```
@misc{https://doi.org/10.48550/arxiv.2209.10702,
  doi = {10.48550/ARXIV.2209.10702},
  
  url = {https://arxiv.org/abs/2209.10702},
  
  author = {Eastman, Peter and Behara, Pavan Kumar and Dotson, David L. and Galvelis, Raimondas and Herr, John E. and Horton, Josh T. and Mao, Yuezhi and Chodera, John D. and Pritchard, Benjamin P. and Wang, Yuanqing and De Fabritiis, Gianni and Markland, Thomas E.},
  
  keywords = {Chemical Physics (physics.chem-ph), Machine Learning (cs.LG), Biomolecules (q-bio.BM), FOS: Physical sciences, FOS: Physical sciences, FOS: Computer and information sciences, FOS: Computer and information sciences, FOS: Biological sciences, FOS: Biological sciences},
  
  title = {SPICE, A Dataset of Drug-like Molecules and Peptides for Training Machine Learning Potentials},
  
  publisher = {arXiv},
  
  year = {2022},
  
  copyright = {arXiv.org perpetual, non-exclusive license}
}
```

**Comment by jchodera** [comment]
One last addition: The README or release notes should mention something about the dataset size and composition---I've already seen requests to describe this, since it only appears in the manuscript, which describes the 1.1 and 1.0 versions of the dataset only (and may not describe future versions).

Here it is in table form for you to copy-and-paste from the Markdown source:

| Subset | Molecules | Conformations | Atoms | Elements |
| ---        | ---             | ---                     | ---       | ---            |
| Dipeptides | 677 | 33850 | 26–60 | H, C, N, O, S |
| Solvated Amino Acids | 26 | 1300 | 79–96 | H, C, N, O, S |
| DES370K Dimers | 3490 | 345676 | 2–34 | H, Li, C, N, O, F, Na, Mg, P, S, Cl, K, Ca, Br, I |
| DES370K Monomers | 374 | 18700 | 3–22 | H, C, N, O, F, P, S, Cl, Br, I |
| PubChem | 14643 | 731856 | 3–50 | H, C, N, O, F, P, S, Cl, Br, I |
| Ion Pairs | 28 | 1426 | 2 | Li, F, Na, Cl, K, Br, I |
| **Total** | **19238** | **1132808** | **2–96** | **H, Li, C, N, O, F, Na, Mg, P, S, C** |

**Comment by peastman** [comment]
I already added the DOI to the release.  Not the badge, but I think just having the URL makes it easier to copy and paste.

> The README or release notes should mention something about the dataset size and composition

Good idea.

**Comment by jchodera** [comment]
> I already added the DOI to the release. Not the badge, but I think just having the URL makes it easier to copy and paste.

The DOI/URL isn't cited directly---it just takes you to the page with the tools to export the citation in the appropriate format for your reference manager.

**Comment by jchodera** [comment]
I realize we neglect to mention the level(s) of theory provided in the dataset in the README as well. We might want to give the primary level of theory (the one used by the downloader) but note than a level of theory that is compatible with the [Open Force Field Initaitive](http://openforcefield.org) force fields is also available in QCArchive.

**Comment by peastman** [comment]
> I realize we neglect to mention the level(s) of theory provided in the dataset in the README as well.

It's there.  "SPICE computations are done at the ωB97M-D3BJ/def2-TZVPPD level of theory."

**Comment by peastman** [comment]
I'm going to merge this now to get the information online.  We can make further changes in other PRs.

**Pull request merged**
